### ISSUE TITLE
Support of JSR-318 - Interceptors

### ISSUE THREAD

**Issue by hwilming** [techatspree/needle#10]
Interceptor binding of methods of the object under test should be considered.

Needle API to enbale Interceptor execution:

``` java
public class Test{
@Rule public NeedleRule ...

@ObjectUnderTest
private MyComponent objectUnderTest;


@de.akquinet.jbosscc.needle.Interceptor(Loggable.class)
private LoggerInterceptor interceptor;

...
}
```

**Comment by jangalinski** [comment]
I cannot really see, what the benefit would be? It will be extremly hard and error-prone to implement interceptor handling on the objects-under-test, this would bend the scope of testing "units", where needle is strong, and enter the world of integration where such tools arquillian already offer this functionality.

Judging from the example given, the interceptor concept addresses just the test classes itself ... so it provides an opportunity to do something before or after a test method is executed. 
Thats exactly what rules already do. So why does needle need a new concept for that? Especially when looking at the "new" RuleChain feature of junit that needle already supports since 2.2.

Please don't get me wrong: I have nothing against an interceptor feature, and might even use it, but I dont get why this feature is a 2.3-milestone ...

**Comment by hwilming** [comment]
I agree with you. I implemented a spike and it is really complex and error prone. This kind of test should be an integration test. So I reject this issue.
