### ISSUE TITLE
Override Needle default configuration

### ISSUE THREAD

**Issue by hwilming** [techatspree/needle#15]
It should be possible to override the default needle configuration from the needle.properties.

For example, through annotations:

``` java
@NeedleConfiguration(mockProvide=MockitoProvider.class, ...)
@DatabaseConfiguration(persistenceUnit="TestUnit", ...)
```

**Comment by jangalinski** [comment]
The main issue is, that NeedleConfiguration and ConfigurationLoader do a lot of "hidden" work with hard coded file names and static values. No matter how we actually configure the rule, we first must reorganize the configuration structure so it allows passing of different filenames and setting of arbitrary values. I started with NeedleConfiguration, It will look like this:

``` java
private final Map<String,String> properties;

public NeedleConfiguration() { 
this("needle")
}
public NeedleConfiguration(String resourceName) {
this(Classloader.load....(resourceName)) 
}
public NeedleConfiguration(Map<String,String> properties) {
this.properties = properties;
// init stuff here
}
```

this way, we keep the default behavior but allow passing of different files/values. This will have to be passed up to NeedleTestCase and NeedleTestRule. Then I could configure like:

``` java
@Rule
public final NeedleRule needle = new NeedleRule("my-needle-file"); // or new NeedleRule().withFile("myneedlefile").
// or even with a Builder NeedleRule.withMockProvider(...).withProperty(...)
```

I dont like using annotations for this because:
- To access the annotation value, the rule must know the test instance or class (like with NeedleTestRule)
- The Configuration is an "on create" activity and thus belongs in a constructor or Builder.
- Annotating the test class separates rule creation and configuration which is less readably especially when I use more then one Rule and/or constants and setup in my test.

My preferred approach would be the builder, because it keeps the constructors from bloating and allows easy default behavior for those (99%?) of the cases where I dont need to override needle.properties.

**Comment by jangalinski** [comment]
Did you find the time to look into this?

**Comment by hwilming** [comment]
Now the Rules are configurable with a individual property files by the RuleBuilder (see #26).

@Rule
 public NeedleRule needle = new NeedleRuleBuilder().with("needle-mockito").build();

@Rule
public DatabaseRule = new DatabaseRuleBuilder().with("custom-db-config").build();
